---
title: ''
author: "Natalia Lamberova"
email: Natalia.Lamberova@UTDallas.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=.75in
jobtitle: Assistant Professor of Business and Technology, University of Texas at Dallas
keywords: R Markdown, academic CV, template
linkcolor: Brown
fontawesome: yes
address: Cecil H. Green Hall | 800 West Campbell Road, GR 3.822 | Richardson, TX 75080-3021
updated: no
urlcolor: Brown
web: natalialamberova.com
xcolor: yes
---



# EDUCATION

**University of California, Los Angeles**, PhD in Government  \hfill 2020

\hskip 1cm  Topic: "*Political Economy of Technological Development*"

\hskip 1cm  Committee: Prof. Daniel Treisman (chair),

\hskip 1cm Prof. Chad Hazlett, Prof. Daniel Posner, Prof. Nico Voigtlander (Anderson School of Management)

**University of California, Los Angeles**, MSc in Statistics  \hfill 2020

**Kazan Federal University, Kazan**, BA in Economics (with Honors)  \hfill 2010

**Washington University, St. Louis**, Visiting student \hfill 2008-9

# ACADEMIC POSITIONS

**Assistant Professor of Business and Technology**, School of Economic, Political and Policy Sciences, University of Texas at Dallas,  \hfill 2022-now

**Postdoctoral Fellow**, Center for International Strategy, Technology and Policy,  \hfill 2020-22

Sam Nunn School of International Affairs, Georgia Institute of Technology

**Teaching Fellow**, Anderson School of Management, UCLA \hfill 2018-19

**Research Fellow**, **Teaching Fellow**, Department of Political Science, UCLA \hfill 2014-17

**Teaching Assistant**, Department of Economics, University of Maryland \hfill 2012-14

**Research Fellow**, Center for the Study of Institutions and Development, \hfill 2013

Moscow Higher School of Economics  

**Lecturer**, Economics Department, Kazan National Technological Research University \hfill 2010-12 

# RESEARCH

## Articles

[**"Information Manipulation and Repression: Theory and Evidence from the COVID-19 Response in Russia"**](https://doi.org/10.1016/j.jpubeco.2026.105740), with Konstantin Sonin, *Journal of Public Economics*, 262 (2026), 105740. [PDF](https://natalialamberova.com/files/Lamberova_Sonin_Information_Manipulation_Repression.pdf)

[**"The Causal Effect of Pet Ownership on Health and Well-being"**](https://doi.org/10.1007/s11482-026-10550-5), with Maxim Ananyev, Ferdi Botha, and Kyle Peyton, *Applied Research in Quality of Life*, 21 (2026): 781-795. [PDF](https://natalialamberova.com/files/Ananyev_Botha_Lamberova_Peyton_Pet_Ownership.pdf)

[**"R&D Investment and Political Connections: Complements or Substitutes? Evidence from Russia"**](https://doi.org/10.1080/1406099X.2025.2540688), *Baltic Journal of Economics*, 25(2) (2025): 201-231. [PDF](https://natalialamberova.com/files/Lamberova_RD_Investment_Political_Connections.pdf)

[**"The Paradox of Government-Funded Innovation in Weakly Institutionalized Environments"**](https://doi.org/10.1016/j.jik.2024.100536), *Journal of Innovation & Knowledge*, 9(3) (2024), 100536. [PDF](https://natalialamberova.com/files/Lamberova_Paradox_Government_Funded_Innovation.pdf)

[**"#Polarized: Gauging Potential Policy Bargaining Ranges Between Opposing Social Movements of Black Lives Matter and Police Lives Matter"**](https://www.mdpi.com/2076-0760/13/11/604) in *Social Sciences, 2024* (with DeFusco et al)

[**"The Puzzling Politics of R&D: Signaling Competence through Risky Projects"**](https://doi.org/10.1016/j.jce.2021.01.002), *Journal of Comparative Economics*, 49(3) (2021): 801-818. [PDF](https://natalialamberova.com/files/Lamberova_Puzzling_Politics_RD.pdf)

[**"Stability of Revolutionary Governments in the Face of Mass Protest"**](https://doi.org/10.1016/j.ejpoleco.2019.08.003), with Dmitry Dagaev and Anton Sobolev, *European Journal of Political Economy*, 60 (2019), 101812. [PDF](https://natalialamberova.com/files/Dagaev_Lamberova_Sobolev_Revolutionary_Governments.pdf)

[**"Economic Transition and the Rise of Alternative Institutions: Political Connections in Putin's Russia"**](https://doi.org/10.1111/ecot.12167), with Konstantin Sonin, *Economics of Transition*, 26(4) (2018): 615-648. [PDF](https://natalialamberova.com/files/Lamberova_Sonin_Economic_Transition.pdf)


## Peer-reviewed book chapters

[**"Putin’s Strategy After the Global Financial Crisis of 2008-9"**](https://doi.org/10.3998/mpub.11354716) in *Economic Shocks and Authoritarian Stability: Duration, Financial Conditions, and Institutions*, 2020, 97-118, University of Michigan Press (with Daniel Treisman)

[**"The Role of Business in Shaping Economic Policy"**](www.jstor.org/stable/10.7864/j.ctt1zkjzsh.9) in *The New Autocracy: Information, Politics, and Policy in Putin's Russia*, 2018, 249-276, Brookings Institution Press (with Konstantin Sonin)


## Working Papers (under review)


**"Patent Protection, Funding Access, and Resilience of Software Startups: Analyzing the Impact of the Alice Decision"** (with Maxim Ananyev)

**"Public Support for Long-term Military Investments during Wartime: Evidence from Ukraine"** (with Vera Mironova and Sam Whitt)

**"Public Perspectives on War Trauma Research: Evidence from Ukraine"** (with Vera Mironova and Sam Whitt)

## Research in progress 

**"Searching for Data Privacy: Evidence from GDPR"** (with Kristine Thomas)

**"When Politically Congruent Opinions Pass for Facts: Self-Worth and Motivated Classification in Media Environments"** (with Alexei Zakharov, Sydney Brown, and Minh Dao)

**"Research or Mesearch? Do Personal Experiences Drive Research Agendas of Social Scientists"** (with Mikhail Galashin and Venkatesh Subramanian)

**"War and Technology: Investigating the Impact of Conflict Exposure on Attitudes Toward R&D Investment in Ukraine"** (with Vera Mironova)





<!--
[**"A friend of a friend: the evolution of positive country-to-country relations"**](#published-works)(with Arthur Stein, Robert F. Trager) 

[**"Measure for Measure: Using Events Data to Characterize Relationships in Networks"**](#published-works)(with Arthur Stein, Robert F. Trager)

[**"Leaderless Protests"**](#published-works) (with Dmitry Dagaev, Anton Sobolev, and Konstantin Sonin)

-->

# SELECTED GRANTS & FELLOWSHIPS
<!-- 
## External (while at UCLA)
Institute for Humane Studies, Arlington, 2020 Summer Graduate Research Fellowship 2020

## External
The grant of President of Tatarstan for the outstanding graduate research \hfill 2012

"Algarysh" grant of Tatarstan Republic to study in Washington University in St. Louis with full tuition coverage and stipend \hfill 2008-2009

## Internal (at UCLA)

UCLA Fellowship \hfill 2014

UCLA Dean's Stipend \hfill 2014

--> 


Institute for Humane Studies, Arlington, Hayek Grant  \hfill 2018-25

Dissertation Year Fellowship, UCLA \hfill 2019-2020

Institute for Humane Studies, Arlington, PhD Fellowship  \hfill 2015, 2017-20 

Dissertation Research Fellowship,  \hfill 2018-19

Center for European and Russian Studies, UCLA

Charles Koch Graduate Student Grant \hfill 2018 

The Harriman Institute, Columbia University, Travel Grant  \hfill 2018-19 

The Harriman Institute, Columbia University, Research Grant  \hfill 2018 

Global Development Network CIS Department Development Grant \hfill 2012

Ronald Coase Institute Fellowship \hfill 2011


# SELECTED PRESENTATIONS

## Invited Talks

\hskip 1cm Political Economy Workshop at the Harris School, University of Chicago (2025), 

\hskip 1cm Georgia Institute of Technology (2023), 

\hskip 1cm Computational International Relations Workshop (UCLA, 2020), 

\hskip 1cm IHS Graduate Workshop (George Mason University, 2019), 

\hskip 1cm Political Economics Workshop (Moscow Higher School of Economics, 2018, 2019)
<!-- 
, ,Great Power Competition in the 21st Century Workshop (2021), International Center for the Study of Institutions and Development Conference, Higher School of Economics(2020),IHS SURF Workshop (2020), Invited talk at UCLA Computational International Relations Workshop (2020),ASSA (2020), Joint Seminar of Higher School of Economics on Political Economy, ICSID and NES CSDSI (2019),

Invited talk at IHS Graduate Workshop at George Mason University (2019), Geo-Economic and Geostrategic Dimensions of Great Power Competition in the 21st Century" Summer Training Course (2019), WPSA (2019),  International Center for the Study of Institutions and Development Conference, Higher School of Economics (2019, 2018),  April International Academic Conference On Economic and Social Development (2013, 2012, 2010, 2011), Moscow Higher School of Economics (2014), UCLA (2014,2015,2016)
-->

## Select conferences

ASSA (2026, 2025, 2024,2020,2021); Polmeth (2025, 2024, 2019); Evidence-based research in Ukraine's development (online, 2024,2025); APPAM (2024); Society for Institutional and Organizational Economics Conference (2024, 2021); APSA (2014, 2016, 2018, 2021,2022); MPSA (2014-25); Corruption, Tax Evasion and Institutions Conference (Stockholm School of Economics, 2021);WPSA (2018-19); 7th Annual Comparative Politics and Formal Theory Conference (2019); European Economic Association Annual Conference (2015)





# TEACHING EXPERIENCE

University of Texas at Dallas, *School of Economic, Political and Policy Sciences*

\hskip 1cm Political Economy of Development (Graduate)  (2024)

\hskip 1cm Game Theory for Political Science (Graduate)  (2024)

\hskip 1cm Innovation Economy (Graduate) (2023, 2024,2025)

\hskip 1cm Research Design II (Causal Inference, Graduate) (2023, 2024, 2025)

\hskip 1cm Topics in Science, Technology and Institutions: from Writing to Cryptocurrency (2025,2024, 2022)

**Georgia  Institute of Technology**, ***Sam Nunn School of International Affairs***             

\hskip 1cm Economics of International Security (2020)

\hskip 1cm Political Economy of Post-Communism (2020-21)

**University of California, Los Angeles**, ***Anderson Business School***

\hskip 1cm Technology Analytics, with Prof. Keith Chen (2019)

\hskip 1cm Competitive Analytics, with Prof. Keith Chen (2019)

**University of California, Los Angeles**, ***Department of Political Science***

\hskip 1cm Politics and Government of Post-Communist Russia, with Prof. Daniel Treisman (2015-17)

\hskip 1cm Politics and Strategy, with Prof. Barry O'Neil and Prof. Kathleen Bawn (2015, 2018)

\hskip 1cm Experiments and Research Design, with Prof. Graeme Blair (2016)

\hskip 1cm Peace and War, with Prof. Daborah Larson (2015)

\hskip 1cm World Politics, with Prof. Leslie Johns (2015)


# SERVICE

**Research and University Leadership**

- Director, Origins of Ideas Research Lab, University of Texas at Dallas
- Co-Chair, Innovation Destination Initiative, Roadmap 2030, University of Texas at Dallas

**Professional Service**

- National Science Foundation --- Panelist, 2024--2025 (multiple panels)

**Faculty Committees**

- Intellectual Property Advisory Committee for UTD, 2005-2006
- Ranking Committee for PPPE at EPPS, 2026
- Hiring Committee for Associate or Full Professor of Political Science at EPPS, 2024
- Hiring Committee for Associate or Full Professor of International Relations at EPPS, 2024
- Methods Qualifying Examination Committee, 2023-now



**Manuscript Referee**: Business and Politics, PLOS ONE, Journal of Economic Behavior and Organization, American Political Science Review, Journal of Comparative Economics, Economics of Transition, Journal of Public Policy, Science and Public Policy, Journal of Institutional Economics.

<!--
**Methods Workshops at Economics Department, Kazan National Research Technological University**:                  

Causal Inference Workshop \hfill 2019                                   
R Workshop  \hfill 2018, 2019                    
Game Theory Workshop \hfill 2018             

-->

# SKILLS

**Software:**  R (`keras`,  `selenium`,  `rvest`,  `tm`,  `ggplot2`,  `statnet`,  `sp`,  `raster`, `daggity`, `gis`),

\hskip 1.9 cm  Stata,  \LaTeX

**Languages:** Russian (fluent), French (basic proficiency)

<!--

DATA COLLECTION: automated data extraction, automated text processing,

\hskip 1.9 cm online and field experiments, surveys, interviews
-->
